<?php
$z[0]=Array("global","",40,63);
$z[0][4]['name']="cfg_tips";
$z[1]=Array("field","",204,229);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",367,392);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",426,451);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("channel","	\r\n							<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n						",876,1000);
$z[4][4]['type']="top";
$z[4][4]['row']="10";

?>