<?php
$z[0]=Array("include","",0,37);
$z[0][4]['filename']="header.htm";
$z[1]=Array("global","",129,156);
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("channelartlist"," \r\n        	\r\n			<li>\r\n				<a href=\"{dede:field name='typeurl'/}\" >\r\n					{dede:field name='typename'/}\r\n				\r\n				</a>\r\n				\r\n            	<div class=\"subMenu fix-png\">\r\n				{dede:channel type='son' noself='yes'}\r\n				\r\n                \r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                \r\n				\r\n				\r\n            \r\n			\r\n				{/dede:channel}\r\n				</div>\r\n				\r\n			</li>\r\n     \r\n        ",208,703);
$z[2][4]['typeid']="2,3,4,5,6";
$z[2][4]['row']="8";
$z[3]=Array("global","",1914,1946);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",2015,2047);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",2184,2216);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",5301,5338);
$z[6][4]['filename']="footer.htm";

?>